### ISSUE TITLE
Search bar refining

### ISSUE THREAD

**Issue by JAYESH-555** [Someshsw1109/SRC-Mart#1]
Currently, the Search here is not visible in the search bar. Have to adjust a bit accordingly. 
![image](https://github.com/user-attachments/assets/1298308f-6e3e-45ca-a2f5-5ee52db0655f)

**Comment by Someshsw1109** [comment]
![Screenshot 2024-12-06 144403](https://github.com/user-attachments/assets/9d011235-61e0-42c4-8f1e-d20d8f33e956)


Now issue is fixed.
