### ISSUE TITLE
Signup Notification Issue

### ISSUE THREAD

**Issue by Someshsw1109** [Someshsw1109/SRC-Mart#2]
![Screenshot 2024-12-06 145748](https://github.com/user-attachments/assets/0886c4dd-b6fb-426e-a82a-ff0809468375)

Please Look into this issue whenever we signed up it shows firstly signup failed and then after few seconds it shows signup successfully.

**Comment by JAYESH-555** [comment]
Closing this issue as - https://github.com/Someshsw1109/SRC-Mart/pull/3 this PR fixed the issue.
